### PR TITLE
ballle98/AqualinkD#42: memcpy-param-overlap in PDA Shift processing

### LINKED ISSUE #86: memcpy-param-overlap in PDA Shift processing
see ballle98/AqualinkD#42: memcpy-param-overlap in PDA Shift processing

```
21:50:02.849 Notice:   To 0x62 of type PDA Shif | HEX: 0x10|0x02|0x62|0x0f|0x01|0x08|0xff|0x8b|0x10|0x03|
=================================================================
==8955==ERROR: AddressSanitizer: memcpy-param-overlap: memory ranges [0x00622105,0x0062219e) and [0x00622116, 0x006221af) overlap
    #0 0x566e7 in __interceptor_memcpy.part.36 (/home/pi/remote-debugging/aqualinkd+0x566e7)
    #1 0x126643 in process_pda_menu_packet C:\git\AqualinkD/pda_menu.c:253
    #2 0x124f57 in process_pda_packet C:\git\AqualinkD/pda.c:529
    #3 0xf69b3 in process_packet C:\git\AqualinkD/aqualinkd.c:530
    #4 0xf9b9f in main_loop C:\git\AqualinkD/aqualinkd.c:1148
    #5 0xf814b in main C:\git\AqualinkD/aqualinkd.c:810
    #6 0xb6ce1677 in __libc_start_main (/lib/arm-linux-gnueabihf/libc.so.6+0x16677)

AddressSanitizer can not describe address in more detail (wild memory access suspected).
AddressSanitizer can not describe address in more detail (wild memory access suspected).
SUMMARY: AddressSanitizer: memcpy-param-overlap (/home/pi/remote-debugging/aqualinkd+0x566e7) in __interceptor_memcpy.part.36
==8955==ABORTING
```

### PR DESCRIPTION
**Pull request by ballle98**
fix #86 

see see ballle98#42: memcpy-param-overlap in PDA Shift processing

### CODE REVIEW

File: pda_menu.c [hunk 1]
```diff
@@ -200,9 +205,25 @@ bool process_pda_menu_packet(unsigned char* packet, int length)
       if (getLogLevel() >= LOG_DEBUG){print_menu();}
     break;
     case CMD_PDA_SHIFTLINES:
-      memcpy(_menu[1], _menu[2], (PDA_LINES-1) * (AQ_MSGLEN+1) );
+      // press up from top - shift menu down by 1
```
Comment (ballle98) [inline pda_menu.c]: This is the fix the other code is to test the fic
